name: Automated review

on: [push]

jobs: 
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      #- name: Run prettier check
      #  run: npm run check

  build-container:
    runs-on: ubuntu-latest
    needs: quality-check
    env:
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}     
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/angular-todos-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Build docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag $IMAGE_NAME:$TAG_DYNAMIC \
          --tag $IMAGE_NAME:latest

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image to docker hub
        run: |
          docker push $IMAGE_NAME:$TAG_DYNAMIC
          docker push $IMAGE_NAME:latest
